### ISSUE TITLE
console.error overlay does not support DOMExceptions

### ISSUE THREAD

**Issue by rocifier** [devloco/react-scripts-wptheme-error-overlay#1]
Normally this would log to the console fine:

    try {
        // will cause a DOMException
        document.querySelectorAll("div:foo");
    } catch(e) {
        console.error(e, {additionalInfo: "property"});
    }

But with the wpThemeOverlay it doesn't get logged properly (the first exception object is not converted to a string), but instead the following error happens in the logging logic of wpThemeErrorOverlay.js:

    Type error: cannot read property 'substr' of undefined.

**Comment by devloco** [comment]
Unfortunately Facebook changed the error overlay, and it's much harder to figure out how to implement it into another project. Here's one of several issues filed with them to that effect (the one that I've commented on):

[react-error-overlay doesn't show for certain runtime errors](https://github.com/facebook/create-react-app/issues/4760)

I keep hoping they'll fix it such that I can just remove wpThemeOverlay and add their project directly to this one. Otherwise, it's gonna take a deep dive into the FB code to figure out why theirs works with these types of errors and how to replicate that into wpThemeOverlay.

Apologies... but I think it's going to be a while before this one gets fixed...

**Comment by devloco** [comment]
If you're interested, you can keep up with the ticket I filed for myself on the main project here:
[Error Overlay Is Not Invoked When There Is a Client-Side Error](https://github.com/devloco/create-react-wptheme/issues/6)

It's mostly notes to myself as I try to find enough time on the weekends to get this issue fixed.

**Comment by rocifier** [comment]
That sounds tricky. No urgency, as I can break on exceptions and read back in the stack trace for now. But as long as we keep chipping away at this :) your library is really great and is worth maintaining well!

**Comment by devloco** [comment]
Well I took a while to take a look at this. It's a complicated piece code down in there... I threw errors at it all day long, and it just won't build the Error Iframe unless it comes from Webpack (hence why BUILD errors work just fine) or from their own code which is tied into the Webpack Dev Server (which is why RUNTIME errors don't present for this project).

I thought about forking their code... but honestly it is so complex that building something from scratch would take less time.

But getting a blank screen when you have a runtime error is just really annoying! So I slapped an error event listener in the code. **I haven't published it into NPM yet**, I want to mull it over some more. But this is what is checked into the repo here on Github:

![2019-02-10 20_43_23](https://user-images.githubusercontent.com/40293912/52544328-d89b7100-2d75-11e9-9a25-127f75c1bdff.png)

Unfortunately I can't get the correct line number for the error since it comes out of the final compiled file. Which is why I don't print it to screen, but the JS console does show the correct line number... weird.

**Comment by rocifier** [comment]
Thanks so much for spending the time on this. It looks better to see any kind of error happening. The error that was happening for me was even worse. There was an error in the console for me, but I was only seeing [Object object] and was not able to see really anything useful in Chrome. I wonder if it's because you are running a different web browser that it's showing you a better error description there? Any ideas why I wasn't able to see any error description at all without stepping back in the stack trace and inspecting items? Granted my example above is pretty contrived, and the real error I was seeing was coming from a 3rd-party js library.

Did you visit the link in the error about "error boundaries"? What are those? Relevant?

**Comment by devloco** [comment]
Well, in the pictured browser, I'm not doing any console.loggging at all. Both the errors you see they come from:

1. The first one is from create-react-app's error overlay (lol... as a side note, when you code something called "proxyConsole" ... dang... seriously, it's complex in there).
2. React itself is actually logging that second error, which is why the line number is correct.

So, just a guess here, but if you get [Object object]... my guess you'll see that in any browser.

In my day job, we only just started exploring Error Boundaries in the new React, and yah, it's cool. Definitely check it out. It brings server-side-like error handling to React client-side.

**Comment by devloco** [comment]
For the [Object object] thing, you can always try the ol' JSON trick... doesn't always work, but:

`console.log(JSON.stringify(MyObject));`

Or in case the object itself doesn't look JSONish:
`console.log(JSON.stringify({myObject: MyObject}));`

**Comment by rocifier** [comment]
Yeah, the problem is the third party library is not using console.log either, it's just throwing a DOMException. That's not getting through the facebook code properly and formatting the error message.

**Comment by devloco** [comment]
Just an update for anyone who comes along: it looks like Faacebook is in the process of adding some neat new features that should fix this whole mess. Their master branch already has the changes, but they haven't published them to NPM yet.

I'm in the process of updating `create-react-wptheme` to match `create-react-app` v2.1.5.

Hopefully they next time they publish a new version to NPM, all the overlay changes will be in place. At that time, I'll get to work to bring this project's overlay up-to-date.

**Comment by rocifier** [comment]
Nice one, thanks for the updated info.

**Comment by devloco** [comment]
Hi @rocifier,

This looks fixed to me with all the latest code, so I'm going close, but feel free to open a new ticket if needed.

Thanks for the help.
